### ISSUE TITLE
demo_graph.py error in pytorch 0.3.1

### ISSUE THREAD

**Issue by maosengshulei** [lanpa/tensorboard-pytorch#122]
Traceback (most recent call last):
  File "demo_graph.py", line 56, in <module>
    w.add_graph(model, (dummy_input, ))
  File "/home/paperspace/DL/tensorboard-pytorch/tensorboardX/writer.py", line 419, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/paperspace/DL/tensorboard-pytorch/tensorboardX/graph.py", line 67, in graph
    trace, _ = torch.jit.get_trace_graph(model, args)
AttributeError: module 'torch.jit' has no attribute 'get_trace_graph'

**Comment by hustzxd** [comment]
```
python version: 3.6.4
PyTorch version: 0.3.1
Traceback (most recent call last):
  File "demo_graph.py", line 60, in <module>
    w.add_graph(model, (dummy_input, ))
  File "/home/zhaoxiandong/anaconda3/lib/python3.6/site-packages/tensorboardX-1.1-py3.6.egg/tensorboardX/writer.py", line 419, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/zhaoxiandong/anaconda3/lib/python3.6/site-packages/tensorboardX-1.1-py3.6.egg/tensorboardX/graph.py", line 67, in graph
    trace, _ = torch.jit.get_trace_graph(model, args)
AttributeError: module 'torch.jit' has no attribute 'get_trace_graph'
```
I meet the same error.

**Comment by lanpa** [comment]
HI Please use latest pytorch 0.4 if you install tensorboardX from source. `tensorboardX==1.1` from pypi should be good with pytorch 0.3.1

**Comment by hustzxd** [comment]
Oh, it works! Thank you.

**Comment by JackHenry1992** [comment]
@lanpa 
I meet this error with pytorch0.3.1 built from source and tensorboardX==1.1.
![image](https://user-images.githubusercontent.com/9390228/38988177-d2934568-4404-11e8-9cad-42576aa3749c.png)

**Comment by lostork** [comment]
Thank you for the tensorboardX.
I install tensorboardX from pip (so It should be from pypi) and upgrade torch from 0.3.0 to 0.3.1, but I still have errors when running demo_graph.py:

```
Python 2.7.10
torch (0.3.1)
torchvision (0.2.0)
tensorboard (1.7.0)
tensorboardX (1.1)
 python demo_graph.py
Traceback (most recent call last):
  File "demo_graph.py", line 56, in <module>
    w.add_graph(model, (dummy_input, ))
  File "/Users/mayifeng/tracking/tensorboard-pytorch/tensorboardX/writer.py", line 400, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/Users/mayifeng/tracking/tensorboard-pytorch/tensorboardX/graph.py", line 67, in graph
    trace, _ = torch.jit.get_trace_graph(model, args)
AttributeError: 'module' object has no attribute 'get_trace_graph'
```

Is the python version(2.7) the problem?

**Comment by hustzxd** [comment]
Maybe the PyToch version is the key point. You can try PyTorch 0.4.

**Comment by JackHenry1992** [comment]
I test pytorch0.3.1 (use pip install, not build from source ) with python3.5, tensorboardX1.1, and also get this error.
![image](https://user-images.githubusercontent.com/9390228/38997729-b962b47c-4420-11e8-9043-30de94779130.png)

**Comment by lanpa** [comment]
Found that your tensorboardX1.1 is from master: line 67 is different from the one I sent to PyPI. Please uninstall and install again (`pip install tensorboardX`).

**Comment by lanpa** [comment]
Since I am going to drop `add_graph` for pytorch<0.4, closing this.  https://github.com/lanpa/tensorboard-pytorch/pull/106#issuecomment-384534992
