### ISSUE TITLE
problem with displaying embedding

### ISSUE THREAD

**Issue by osm3000** [lanpa/tensorboard-pytorch#130]
Hi,

I using tensorboardX 1.1 with pytorch 0.3.1. The `demo.py` script works fine. But when I display the embeddings, nothing appear, and I get this error message in the terminal

```
Exception happened during processing of request from ('147.171.70.16', 39420)
Traceback (most recent call last):
  File "/localdata/mohammom/anaconda3/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/localdata/mohammom/anaconda3/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/backend/handler.py", line 102, in __init__
    BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, *args)
  File "/localdata/mohammom/anaconda3/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/localdata/mohammom/anaconda3/lib/python3.6/http/server.py", line 420, in handle
    self.handle_one_request()
  File "/localdata/mohammom/anaconda3/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/backend/handler.py", line 530, in do_GET
    self.data_handlers[clean_path](query_params)
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 282, in _serve_runs
    request.respond(list(self.configs.keys()), 'application/json')
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 149, in configs
    self._augment_configs_with_checkpoint_info()
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 167, in _augment_configs_with_checkpoint_info
    tensor = _read_tensor_file(embedding.tensor_path)
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 57, in _read_tensor_file
    for line in f:
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 162, in __next__
    return self.next()
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 156, in next
    retval = self.readline()
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 123, in readline
    self._preread_check()
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/localdata/mohammom/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/localdata/mohammom/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: 00000/tensors.tsv
```

Any help?

**Comment by lanpa** [comment]
What's the result of `pip list|grep tensor`?

**Comment by lanpa** [comment]
Oh, 1.0.1 is pretty old. Can you try with v1.7?
