### ISSUE TITLE
ImportError: cannot import name 'SummaryWriter'

### ISSUE THREAD

**Issue by acgtyrant** [lanpa/tensorboard-pytorch#19]
I do not use anaconda, I install tensorboard-pytorch and tensorflow py pip in the virtual enviroment.

I tried, `from tensorboard import SummaryWriter`, it complains as the title. However, I find the SummaryWriter is in the writer.py in tensorboard, so I have to use `from tensorboard.writer import SummaryWriter`. Where am I wrong?

**Comment by lanpa** [comment]
I think it's the same case as mentioned in #17, and 
`pip install tensorboardX` should solve the problem.

**Comment by acgtyrant** [comment]
You are right.

**Comment by YangSN0719** [comment]
from tensorboard import summary as summary_lib
from tensorboard.plugins.custom_scalar import layout_pb2

**When I was running the following command, an error occurred. I'm sorry to bother you, but please help me anyway**

(n2n) [410@mu01 noise2noise-master]$ python config.py validate --dataset-dir=datasets/kodak --network-snapshot=results/network_final-gaussian-n2c.pickle
Traceback (most recent call last):
  File "config.py", line 14, in <module>
    import validation
  File "/home/410/ysn/noise2noise-master/validation.py", line 16, in <module>
    import dnnlib.tflib.tfutil as tfutil
  File "/home/410/ysn/noise2noise-master/dnnlib/tflib/__init__.py", line 8, in <module>
    from . import autosummary
  File "/home/410/ysn/noise2noise-master/dnnlib/tflib/autosummary.py", line 28, in <module>
    from tensorboard import summary as summary_lib
ImportError: cannot import name 'summary'

**Comment by lanpa** [comment]
@YangSN0719 It should be from tensorboardX, not tensorboard.

**Comment by vkkhare** [comment]
Hi @lanpa I am getting a similar error for `GlobalSummaryWriter` 

```
ImportError: cannot import name 'GlobalSummaryWriter' from 'tensorboardX' (/srv/home/vkkhare/environments/metaSQL/lib/python3.7/site-packages/tensorboardX/__init__.py)
```

pip freeze 
```
pytorch-transformers==1.2.0
pytz==2019.3
pyzmq==19.0.0
regex==2020.4.4
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
s3transfer==0.3.3
sacremoses==0.0.38
scipy==1.4.1
Send2Trash==1.5.0
sentencepiece==0.1.85
-e git+https://github.com/vkkhare/meta-seq2struct.git@c382ea28ada1ecc7ad2a436a4457a37bfda5533a#egg=seq2struct
six==1.14.0
smart-open==1.10.0
stanford-corenlp==3.9.2
tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post3
tensorboardX==2.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tokenizers==0.5.2
torch==1.4.0
torchtext==0.4.0
torchvision==0.5.0

**Comment by soans1994** [comment]
hello,

i have problem please help 

>>> import tensorboardX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/writer.py", line 223
    logdir: Optional[str] = None,
          ^
SyntaxError: invalid syntax

**Comment by iszff** [comment]
> hello,
> 
> i have problem please help
> 
> > > > import tensorboardX
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/**init**.py", line 5, in 
> > > > from .torchvis import TorchVis
> > > > File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/torchvis.py", line 11, in 
> > > > from .writer import SummaryWriter
> > > > File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/writer.py", line 223
> > > > logdir: Optional[str] = None,
> > > > ^
> > > > SyntaxError: invalid syntax

I meet this too，have you solved this？/(ㄒoㄒ)/~~

**Comment by soans1994** [comment]
> > hello,
> > i have problem please help
> > > > > import tensorboardX
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/**init**.py", line 5, in
> > > > > from .torchvis import TorchVis
> > > > > File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/torchvis.py", line 11, in
> > > > > from .writer import SummaryWriter
> > > > > File "/home/rahul/anaconda3/envs/semseg/lib/python2.7/site-packages/tensorboardX/writer.py", line 223
> > > > > logdir: Optional[str] = None,
> > > > > ^
> > > > > SyntaxError: invalid syntax
> 
> I meet this too，have you solved this？/(ㄒoㄒ)/~~

i installed using conda tensorboardx 2.4

**Comment by lanpa** [comment]
@iszff @soans1994 Please update to python3 for the newer tensorboardX. I should have release the package with a correct metadata. sorry.

**Comment by muthena** [comment]
I installed using conda, and run with pytorch, but the wrong below still, how can solve the problem?

Traceback (most recent call last):
  File "E:\yolo\content\yolov7\train.py", line 21, in <module>
    from torch.utils.tensorboard import SummaryWriter
ImportError: cannot import name 'SummaryWriter' from 'torch.utils.tensorboard' (unknown location)

**Comment by Ahmoudahmed** [comment]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from tensorboardX import SummaryWriter
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/writer.py", line 27, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/proto/event_pb2.py", line 15, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/proto/summary_pb2.py", line 15, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/proto/tensor_pb2.py", line 15, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/home/reeplayer/anaconda3/envs/env38/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by Ahmoudahmed** [comment]
Downgrade protobuf: If upgrading protobuf doesn't solve the issue, you can try downgrading it to a version <= 3.20.x. You can install a specific version like this:
pip install protobuf==3.20
