### ISSUE TITLE
error when using `add_embedding`

### ISSUE THREAD

**Issue by cmhungsteve** [lanpa/tensorboard-pytorch#87]
Hello,

I have been trying the `add_embedding` function, and I have no problem running your example codes like `demo.py` or `demo_embedding.py`. However, I met an error when I tried to add this to my framwork. Here is my code:
`writer.add_embedding(feat_source, metadata=source_label_var.data, label_img=source_data_var.data, global_step=n_iter_train, tag='train')`

And the followings are all the info of the inputs
feat_source: [torch.cuda.FloatTensor of size (128,512) (GPU 0)]
source_label_var: torch.cuda.LongTensor of size (128,) (GPU 0)]
source_data_var: [torch.cuda.FloatTensor of size (128,3,56,56) (GPU 0)]

And here is the error message I got:

> Traceback (most recent call last):
  File "/media/cmhung/MyDisk/Dropbox (GhassanGT)/Steve/PhDResearch/Code/Image-Classification/main.py", line 486, in <module>
    main()
  File "/media/cmhung/MyDisk/Dropbox (GhassanGT)/Steve/PhDResearch/Code/Image-Classification/main.py", line 145, in main
    train(source_loader, target_loader, model, criterion, optimizer, epoch, train_file, train_short_file, alpha)
  File "/media/cmhung/MyDisk/Dropbox (GhassanGT)/Steve/PhDResearch/Code/Image-Classification/main.py", line 298, in train
    writer.add_embedding(feat_source, metadata=source_label_var.data, label_img=source_data_var.data, global_step=n_iter_train, tag='train')
  File "/home/cmhung/.virtualenvs/Myenv/lib/python3.6/site-packages/tensorboardX/writer.py", line 449, in add_embedding
    make_sprite(label_img, save_path)
  File "/home/cmhung/.virtualenvs/Myenv/lib/python3.6/site-packages/tensorboardX/embedding.py", line 21, in make_sprite
    label_img = torch.from_numpy(makenp(label_img))  # for other framework
  File "/home/cmhung/.virtualenvs/Myenv/lib/python3.6/site-packages/tensorboardX/x2num.py", line 15, in makenp
    return pytorch_np(x, modality)
  File "/home/cmhung/.virtualenvs/Myenv/lib/python3.6/site-packages/tensorboardX/x2num.py", line 24, in pytorch_np
    if isinstance(x, torch.autograd.variable.Variable):
AttributeError: 'builtin_function_or_method' object has no attribute 'Variable'

I don't know why `Variable` can't be the input in my case.
I will be appreciative if you can help me resolve this issue.
Thank you so much!!!

**Comment by cmhungsteve** [comment]
Never mind. 
I just found that this problem can be fixed by installing from source.
Ther could be some bugs in the `pip` version.
