### ISSUE TITLE
How to create dummy input to add_graph()?

### ISSUE THREAD

**Issue by smolendawid** [lanpa/tensorboard-pytorch#88]
My attention-based network gets a 2-element list with data and labels. In each, there's a tuple of batch size (the same num for data and labels). Each labels list can have random number of values (timesteps), each data list can have random number of timesteps, but equal number of features, 80.

How can I create dummy_input for add_graph()? It's not clear to me why in the example there's 4d vector..

**Comment by smolendawid** [comment]
The furthest I could go:

```
    dummy_input = torch.autograd.Variable(torch.rand(1, 30, 81))
    dummy_labels = torch.autograd.Variable(torch.rand(1, 5, 1))
    writer.add_graph(model, ((dummy_input, dummy_labels), ))
```
/Users/user/project/speech/speech_env/lib/python2.7/site-packages/torch/onnx/__init__.py:244: UserWarning: ONNX export failed on Constant because torch.onnx.symbolic.Constant does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/user/project/attention/train.py", line 255, in <module>
    run(config, args.target_path, writer, load_model)
  File "/Users/user/project/attention/train.py", line 186, in run
    writer.add_graph(model, ((dummy_input, dummy_labels), ))
  File "/Users/user/project/speech/speech_env/lib/python2.7/site-packages/tensorboardX/writer.py", line 400, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/Users/user/project/speech/speech_env/lib/python2.7/site-packages/tensorboardX/graph.py", line 56, in graph
    torch.onnx._optimize_trace(trace)
  File "/Users/user/project/speech/speech_env/lib/python2.7/site-packages/torch/onnx/__init__.py", line 81, in _optimize_trace
    torch._C._jit_pass_onnx(trace)
  File "/Users/user/project/speech/speech_env/lib/python2.7/site-packages/torch/onnx/__init__.py", line 148, in _run_symbolic_method
    return symbolic_fn(*args)
  File "/Users/user/project/speech/speech_env/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 357, in symbolic
    raise RuntimeError("hack_onnx_rnn NYI")
RuntimeError: hack_onnx_rnn NYI

**Comment by lanpa** [comment]
What's your pytorch version? maybe related to https://github.com/pytorch/pytorch/issues/5234?

**Comment by smolendawid** [comment]
Thanks for the explanation, I forgot about the channels.

I'm using PyTorch 3.1 (pip), TensorboardX 1.1 and MacOS.

Attached link could be fine, but still I don't get which version should I use to get this working (master is currently 3.1?) maybe I'll leave it open unless I'll test newer version?

**Comment by lanpa** [comment]
0.3.1 is not able to export RNN to onnx, so you have to build pytorch from source.

**Comment by smolendawid** [comment]
Well I got some problems with building PyTorch from sources in virtualenv so I can't confirm it's working, but I suspect it is indeed PyTorch thing so the issue can be closed
